### ISSUE TITLE
Error: While trying to resolve module `firebase` 

### ISSUE THREAD

**Issue by affan00733** [scorelab/Go-social#184]
Firebase package is being installed irrespective of it getting the error of Error: While trying to resolve module `firebase`. This  has been occurred in the initialisation of the project.

- Tried to upgrade the firebase package but it didn't worked

Logs : 

error: Error: While trying to resolve module `firebase` from file `/Users/afaanansari/Desktop/gsoc/Go-social/config/config.js`, the package `/Users/afaanansari/Desktop/gsoc/Go-social/node_modules/firebase/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/afaanansari/Desktop/gsoc/Go-social/node_modules/firebase/index`. Indeed, none of these files exist:

  * /Users/afaanansari/Desktop/gsoc/Go-social/node_modules/firebase/index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * /Users/afaanansari/Desktop/gsoc/Go-social/node_modules/firebase/index/index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at DependencyGraph.resolveDependency (/Users/afaanansari/Desktop/gsoc/Go-social/node_modules/metro/src/node-haste/DependencyGraph.js:272:17)
    at Object.resolve (/Users/afaanansari/Desktop/gsoc/Go-social/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/Users/afaanansari/Desktop/gsoc/Go-social/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/Users/afaanansari/Desktop/gsoc/Go-social/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at async Graph._addDependency (/Users/afaanansari/Desktop/gsoc/Go-social/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 11)
    at async Graph._processModule (/Users/afaanansari/Desktop/gsoc/Go-social/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
    at async Graph._addDependency (/Users/afaanansari/Desktop/gsoc/Go-social/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 2)
    at async Graph._processModule (/Users/afaanansari/Desktop/gsoc/Go-social/node_modules/metro/src/DeltaBundler/Graph.js:263:5)

Sample attachments : 

<img width="571" alt="image" src="https://user-images.githubusercontent.com/42251896/227762095-4f3b418c-66fc-441d-a802-ee2c7e78bea6.png">

<img width="365" alt="image" src="https://user-images.githubusercontent.com/42251896/227762126-7c5d03ab-835d-4575-b913-9a63a5b7e7b6.png">

**Comment by affan00733** [comment]
As I am applying this project for GSOC 2023 so , i can address this issue

**Comment by utopian-monkey** [comment]
i have solved this in #188
